apiVersion: apps/v1
kind: Deployment
metadata:
  name: myobjectstorageapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myobjectstorageapp
  template:
    metadata:
      labels:
        app: myobjectstorageapp
    spec:
      containers:
      - name: myobjectstorageapp
        image: eshanks16/myobjectstorageapp:v6
        env:
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
                name: px-os-credentials-s3-pba
                key: access-key-id
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
                name: px-os-credentials-s3-pba
                key: secret-access-key
        - name: S3_BUCKET_NAME
          valueFrom:
            secretKeyRef:
                name: px-os-credentials-s3-pba
                key: bucket-id
        - name: S3_ENDPOINT
          valueFrom:
            secretKeyRef:
                name: px-os-credentials-s3-pba
                key: endpoint
        - name: S3_REGION
          valueFrom:
            secretKeyRef:
                name: px-os-credentials-s3-pba
                key: region
